name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # 当你将更新推送到 main 分支时触发部署

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add origin https://github.com/${{ github.repository }}
          git fetch origin
          git checkout gh-pages || git checkout --orphan gh-pages
          cp -r build/web/* .
          git add .
          git commit -m "Deploy Flutter Web app to GitHub Pages"
          git push origin gh-pages
